### ISSUE TITLE
Error Installing in python 3.10.0

### ISSUE THREAD

**Issue by hanzigs** [timzatko/Sklearn-Nature-Inspired-Algorithms#16]
Hi,
I am upgrading my python to 3.10.0, currently using 3.9.5 where sklearn-nature-inspired-algorithms 0.6.0 working good with scikit-learn==0.24.2.

for py3.10.0, I installed scikit-learn==1.0.2 and sklearn-nature-inspired-algorithms==0.6.1 also tired 0.7.1, I am getting following error while installing
May I have some help please

For now, python 3.10.0 requires scikit-learn > 1.0 but sklearn-nature-inspired-algorithms requires scikit-learn<1.0.0, am I correct?

```
Collecting sklearn-nature-inspired-algorithms==0.6.1
  Using cached sklearn_nature_inspired_algorithms-0.6.1-py3-none-any.whl (9.9 kB)
Collecting niapy==2.0.0rc18
  Using cached niapy-2.0.0rc18-py3-none-any.whl (202 kB)
Collecting toml<1.0.0,>=0.9
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: pandas<2.0.0,>=1.0 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from sklearn-nature-inspired-algorithms==0.6.1) (1.3.5)
Requirement already satisfied: numpy<2.0.0,>=1.18 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from sklearn-nature-inspired-algorithms==0.6.1) (1.22.3)
Collecting seaborn<1.0.0,>=0.10
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting matplotlib<4.0.0,>=3.2
  Using cached matplotlib-3.5.1-cp310-cp310-win_amd64.whl (7.2 MB)
Collecting scikit-learn<1.0.0,>=0.22
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\pg\anaconda3\envs\py3100\python.exe' 'C:\Users\pg\anaconda3\envs\autoMLpy3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\pg~1\AppData\Local\Temp\tmpalz9u3b0'
         cwd: C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_6cde19b09c4e4340ac1e1890ee40a83c
    Complete output (46 lines):
    Partial import of sklearn during the build process.
    INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    Traceback (most recent call last):
      File "C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
        main()
      File "C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 301, in <module>
        setup_package()
      File "setup.py", line 297, in setup_package
        setup(**metadata)
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 188, in configuration
        config.add_subpackage('sklearn')
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1054, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1020, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 962, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_6cde19b09c4e4340ac1e1890ee40a83c\sklearn\setup.py", line 83, in configuration
        cythonize_extensions(top_path, config)
      File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_6cde19b09c4e4340ac1e1890ee40a83c\sklearn\_build_utils\__init__.py", line 45, in cythonize_extensions
        basic_check_build()
      File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_6cde19b09c4e4340ac1e1890ee40a83c\sklearn\_build_utils\pre_build_helpers.py", line 106, in basic_check_build
        compile_test_program(code)
      File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_6cde19b09c4e4340ac1e1890ee40a83c\sklearn\_build_utils\pre_build_helpers.py", line 66, in compile_test_program
        ccompiler.compile(['test_program.c'], output_dir='objects',
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
        self.initialize()
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\pg\AppData\Local\Temp\pip-build-env-ydl3gzk9\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/05/04/507280f20fafc8bc94b41e0592938c6f4a910d0e066be7c8ff1299628f5d/scikit-learn-0.24.2.tar.gz#sha256=d14701a12417930392cd3898e9646cf5670c190b933625ebe7511b1f7d7b8736 (from https://pypi.org/simple/scikit-learn/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\Users\pg\anaconda3\envs\py3100\python.exe' 'C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\pg~1\AppData\Local\Temp\tmpalz9u3b0' Check the logs for full command output.
  Using cached scikit-learn-0.24.1.tar.gz (7.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting openpyxl>=3.0.3
  Using cached openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.2-cp310-cp310-win_amd64.whl (55 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.31.2-py3-none-any.whl (899 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-9.0.1-cp310-cp310-win_amd64.whl (3.2 MB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from matplotlib<4.0.0,>=3.2->sklearn-nature-inspired-algorithms==0.6.1) (2.8.2)
Collecting et-xmlfile
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: pytz>=2017.3 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from pandas<2.0.0,>=1.0->sklearn-nature-inspired-algorithms==0.6.1) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.2->sklearn-nature-inspired-algorithms==0.6.1) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from scikit-learn<1.0.0,>=0.22->sklearn-nature-inspired-algorithms==0.6.1) (3.1.0)
Requirement already satisfied: joblib>=0.11 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from scikit-learn<1.0.0,>=0.22->sklearn-nature-inspired-algorithms==0.6.1) (1.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\pg\anaconda3\envs\py3100\lib\site-packages (from scikit-learn<1.0.0,>=0.22->sklearn-nature-inspired-algorithms==0.6.1) (1.8.0)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\pg\anaconda3\envs\py3100\python.exe' 'C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\pg~1\AppData\Local\Temp\tmpo71jfmah'
       cwd: C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_b8c3a6aeefb843379cf942a042ae963b
  Complete output (48 lines):
  Partial import of sklearn during the build process.
  INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  Traceback (most recent call last):
    File "C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\pg\anaconda3\envs\py3100\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 306, in <module>
      setup_package()
    File "setup.py", line 302, in setup_package
      setup(**metadata)
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "setup.py", line 188, in configuration
      config.add_subpackage('sklearn')
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1054, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1020, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 962, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_b8c3a6aeefb843379cf942a042ae963b\sklearn\setup.py", line 83, in configuration
      cythonize_extensions(top_path, config)
    File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_b8c3a6aeefb843379cf942a042ae963b\sklearn\_build_utils\__init__.py", line 45, in cythonize_extensions
      basic_check_build()
    File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_b8c3a6aeefb843379cf942a042ae963b\sklearn\_build_utils\pre_build_helpers.py", line 106, in basic_check_build
      compile_test_program(code)
    File "C:\Users\pg\AppData\Local\Temp\pip-install-ue3it4ax\scikit-learn_b8c3a6aeefb843379cf942a042ae963b\sklearn\_build_utils\pre_build_helpers.py", line 66, in compile_test_program
      ccompiler.compile(['test_program.c'], output_dir='objects',
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\pg\AppData\Local\Temp\pip-build-env-p6h1bo8u\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn which use PEP 517 and cannot be installed directly
```

**Comment by timzatko** [comment]
Thanks,
fixed in https://github.com/timzatko/Sklearn-Nature-Inspired-Algorithms/releases/tag/v0.8.1
